import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { type CSSSnippet, CSS_COMMENTS } from "../constants";

/* ── CSS output panel with funny comments, copy & download ── */
interface CSSOutputPanelProps {
  appliedSnippets: CSSSnippet[];
}

export function CSSOutputPanel({ appliedSnippets }: CSSOutputPanelProps) {
  const [copied, setCopied] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  /* Generate the full CSS output with funny comments */
  const cssOutput = useMemo(() => {
    if (appliedSnippets.length === 0) return "/* No chaos applied yet. How boring. */";

    const header = [
      "/**",
      " * CSS Un-Center Pro v6.6.6",
      " * Generated by the Layout Destruction Suite",
      " * WARNING: This CSS was created with malicious intent",
      " * DO NOT apply to production. Or do. We're not your boss.",
      " */",
      "",
    ].join("\n");

    const rules = appliedSnippets.map((snippet, i) => {
      const comment = snippet.funnyComment || CSS_COMMENTS[i % CSS_COMMENTS.length];
      const selector = `.un-centered-${snippet.label.toLowerCase().replace(/\s+/g, "-").replace(/^the-/, "")}`;
      const properties = snippet.css.split("\n").map((line) => `  ${line}`).join("\n");
      return `${comment}\n${selector} {\n${properties}\n}`;
    });

    const footer = [
      "",
      "/* === SUMMARY === */",
      `/* Total elements destroyed: ${appliedSnippets.length} */`,
      `/* Layouts liberated: 1 */`,
      `/* Developers traumatized: countless */`,
      "/* Recommended therapy sessions: 12+ */",
    ].join("\n");

    return header + rules.join("\n\n") + footer;
  }, [appliedSnippets]);

  /* Copy CSS to clipboard */
  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(cssOutput);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* Clipboard API unavailable */
    }
  }

  /* Download CSS as file */
  function handleDownload() {
    const blob = new Blob([cssOutput], { type: "text/css" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "un-centered-chaos.css";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <div style={{ marginBottom: "1.5rem" }}>
      <motion.button
        onClick={() => setIsOpen(!isOpen)}
        whileHover={{ scale: 1.01 }}
        style={{
          width: "100%",
          background: "transparent",
          border: "1px solid #00ffff22",
          color: "#00ffff77",
          fontFamily: "monospace",
          fontSize: "0.62rem",
          padding: "0.6rem 0.9rem",
          cursor: "pointer",
          letterSpacing: "4px",
          textAlign: "left",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <span>CSS OUTPUT {appliedSnippets.length > 0 ? `(${appliedSnippets.length} rules)` : ""}</span>
        <span style={{ fontSize: "0.7rem" }}>{isOpen ? "[-]" : "[+]"}</span>
      </motion.button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            style={{ overflow: "hidden" }}
          >
            <div
              style={{
                border: "1px solid #00ffff22",
                borderTop: "none",
                background: "#00ffff05",
              }}
            >
              {/* Action buttons */}
              <div
                style={{
                  display: "flex",
                  gap: "0.5rem",
                  padding: "0.5rem 0.9rem",
                  borderBottom: "1px solid #00ffff11",
                }}
              >
                <button
                  onClick={handleCopy}
                  style={{
                    background: "transparent",
                    border: "1px solid #00ffff33",
                    color: copied ? "#00ff88" : "#00ffff88",
                    fontFamily: "monospace",
                    fontSize: "0.55rem",
                    padding: "0.25rem 0.6rem",
                    cursor: "pointer",
                    letterSpacing: "1px",
                  }}
                >
                  {copied ? "COPIED!" : "COPY"}
                </button>
                <button
                  onClick={handleDownload}
                  style={{
                    background: "transparent",
                    border: "1px solid #00ffff33",
                    color: "#00ffff88",
                    fontFamily: "monospace",
                    fontSize: "0.55rem",
                    padding: "0.25rem 0.6rem",
                    cursor: "pointer",
                    letterSpacing: "1px",
                  }}
                >
                  DOWNLOAD .CSS
                </button>
              </div>

              {/* CSS code display */}
              <pre
                style={{
                  margin: 0,
                  padding: "0.9rem",
                  fontSize: "0.58rem",
                  color: "#00ffff66",
                  lineHeight: "1.7",
                  overflowX: "auto",
                  maxHeight: "300px",
                  overflowY: "auto",
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-all",
                }}
              >
                {cssOutput}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
